import { access, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { runInstall } from "../../src/cli/commands/install.js";
import { runStatus } from "../../src/cli/commands/status.js";
import { runDoctor } from "../../src/cli/commands/doctor.js";
async function exists(path:string){try{await access(path);return true}catch{return false}}

describe("compact headless installation",()=>{
  it("installs the compact kernel, preserves project memory, and is idempotent",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-install-"));await writeFile(join(root,"AGENTS.md"),"User line A\n");await runInstall({directory:root,tools:"codex",skills:"standard",yes:true});for(const rel of [".yaaw-core/system/SYSTEM.md",".yaaw-core/system/kernel.yaml",".yaaw-core/system/engine/runtime.mjs",".yaaw-core/system/roles/orchestrator.md",".yaaw-core/system/modules/changeability.md",".agents/skills/yaaw-orchestrator/SKILL.md"])expect(await exists(join(root,rel))).toBe(true);for(const legacy of ["core","workflows","rules","registries","expertise","tools"])expect(await exists(join(root,".yaaw-core/system",legacy))).toBe(false);expect(await exists(join(root,".yaaw-core/project/state.json"))).toBe(false);const product=join(root,".yaaw-core/project/product.md");await writeFile(product,"durable sentinel\n");await runInstall({directory:root,action:"quick-update",yes:true});expect(await readFile(product,"utf8")).toBe("durable sentinel\n");expect((await runStatus({directory:root,json:true}) as any).healthy).toBe(true);expect((await runDoctor({directory:root,json:true}) as any).healthy).toBe(true)});
  it("installs all Tier-1 providers together",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-multi-"));await runInstall({directory:root,tools:"codex,claude-code,gemini-cli,cline",skills:"core",yes:true});for(const rel of [".agents/skills/yaaw-orchestrator/SKILL.md",".claude/skills/yaaw-orchestrator/SKILL.md",".gemini/skills/yaaw-orchestrator/SKILL.md",".cline/skills/yaaw-orchestrator/SKILL.md",".cline/rules/yaaw-se.md"])expect(await exists(join(root,rel))).toBe(true)});
  it("detects compact framework drift",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-integrity-"));await runInstall({directory:root,tools:"codex",yes:true});const tool=join(root,".yaaw-core/system/engine/integrity.mjs"),healthy=spawnSync(process.execPath,[tool,"--workspace",root],{encoding:"utf8"});expect(healthy.status).toBe(0);const system=join(root,".yaaw-core/system/SYSTEM.md");await writeFile(system,(await readFile(system,"utf8"))+"\nincident edit\n");const drift=spawnSync(process.execPath,[tool,"--workspace",root],{encoding:"utf8"}),report=JSON.parse(drift.stdout);expect(drift.status).toBe(2);expect(report.status).toBe("MODIFIED");expect(report.modified).toContain(".yaaw-core/system/SYSTEM.md")});
  it("backup-replace restores compact framework, preserves durable memory, backs up tainted bytes, and invalidates runtime",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-repair-"));await runInstall({directory:root,tools:"codex",yes:true});const product=join(root,".yaaw-core/project/product.md");await writeFile(product,"durable repair sentinel\n");const system=join(root,".yaaw-core/system/SYSTEM.md"),canonical=await readFile(system,"utf8"),tainted=canonical+"\nincident self-edit\n";await writeFile(system,tainted);const runtime=join(root,".yaaw-core/runtime");for(const name of ["observed-state.json","handoff.json","intent.json","dispatch-failures.json"])await writeFile(join(runtime,name),"{}\n");expect((await runDoctor({directory:root,json:true}) as any).healthy).toBe(false);await runInstall({directory:root,action:"repair",yes:true,conflictPolicy:"backup-replace"});expect(await readFile(system,"utf8")).toBe(canonical);expect(await readFile(product,"utf8")).toBe("durable repair sentinel\n");for(const name of ["observed-state.json","handoff.json","intent.json","dispatch-failures.json"])expect(await exists(join(runtime,name))).toBe(false);const stamps=await readdir(join(root,".yaaw-core/install/backups"));let found=false;for(const stamp of stamps){const candidate=join(root,".yaaw-core/install/backups",stamp,".yaaw-core/system/SYSTEM.md");if(await exists(candidate)){expect(await readFile(candidate,"utf8")).toBe(tainted);found=true}}expect(found).toBe(true);expect((await runDoctor({directory:root,json:true}) as any).healthy).toBe(true)});
  it("safe uninstall preserves durable project memory",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-uninstall-"));await writeFile(join(root,"AGENTS.md"),"keep me\n");await runInstall({directory:root,tools:"codex",yes:true});const product=join(root,".yaaw-core/project/product.md");await writeFile(product,"preserve me\n");await runInstall({directory:root,action:"uninstall",yes:true});expect(await readFile(product,"utf8")).toBe("preserve me\n");expect(await exists(join(root,".yaaw-core/system/SYSTEM.md"))).toBe(false);expect(await exists(join(root,".agents"))).toBe(false);expect(await readFile(join(root,"AGENTS.md"),"utf8")).toBe("keep me\n");expect(await exists(join(root,".yaaw-core/install/uninstalled.json"))).toBe(true)});
  it("requires explicit tools and keeps dry-run mutation-free",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-no-tools-"));await expect(runInstall({directory:root,yes:true})).rejects.toThrow(/requires --tools/i);await runInstall({directory:root,tools:"codex",yes:true,dryRun:true});expect(await exists(join(root,".yaaw-core"))).toBe(false)});
  it("doctor reports a corrupt manifest without rewriting it",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-corrupt-"));await mkdir(join(root,".yaaw-core/install"),{recursive:true});const manifest=join(root,".yaaw-core/install/manifest.json");await writeFile(manifest,"{not-json\n");const report:any=await runDoctor({directory:root,json:true});expect(report.installed).toBe(true);expect(report.manifestValid).toBe(false);expect(await readFile(manifest,"utf8")).toBe("{not-json\n")});
  it("removes manifest-owned legacy semantic paths during update",async()=>{const root=await mkdtemp(join(tmpdir(),"yaaw-layout-migrate-"));await runInstall({directory:root,tools:"codex",yes:true});const manifestPath=join(root,".yaaw-core/install/manifest.json"),manifest:any=JSON.parse(await readFile(manifestPath,"utf8")),canonicalRel=".yaaw-core/system/SYSTEM.md",legacyRel=".yaaw-core/system/core/legacy.md",canonical=await readFile(join(root,canonicalRel));await mkdir(join(root,".yaaw-core/system/core"),{recursive:true});await writeFile(join(root,legacyRel),canonical);manifest.managedFiles[legacyRel]=manifest.managedFiles[canonicalRel];await writeFile(manifestPath,JSON.stringify(manifest,null,2)+"\n");await runInstall({directory:root,action:"quick-update",yes:true});expect(await exists(join(root,legacyRel))).toBe(false);expect(await exists(join(root,".yaaw-core/system/core"))).toBe(false);expect((await runDoctor({directory:root,json:true}) as any).healthy).toBe(true)});
});
