import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { deriveState, planNext } from "../../.yaaw-core/system/engine/routing.mjs";

const kernel=JSON.parse(await readFile(".yaaw-core/system/kernel.yaml","utf8"));
const repo=(digest="sha256:repo")=>({schema:"yaaw.repository-identity/v2",algorithm:"yaaw-worktree-v3",status:"READY",workspace_scope:".",git_root_relation:"same",head_commit:"abc",dirty:true,worktree_digest:digest,components:null,changed_paths:[],error:null});
const doc=(meta:any,path:string)=>({meta,path,digest:`sha256:${path}:${meta.status??"x"}`});
function artifacts(status="READY") { return {product:doc({schema:"yaaw.product/v1",status:"ready",revision:1},".yaaw-core/project/product.md"),engineering:doc({schema:"yaaw.engineering/v2",status:"ready",revision:1,readiness:"PASS",scope_status:"OPEN",current_frontier:"FRONTIER-001"},".yaaw-core/project/engineering.md"),specs:{"SPEC-001":doc({schema:"yaaw.spec/v1",id:"SPEC-001",status:"ACCEPTED",revision:1,product_revision:1,engineering_revision:1},".yaaw-core/project/specs/SPEC-001.md")},tickets:{"TASK-001":doc({schema:"yaaw.ticket/v1",id:"TASK-001",status,revision:1,spec:"SPEC-001",spec_revision:1,product_revision:1,engineering_revision:1,dependencies:[],expertise:[]},".yaaw-core/project/tickets/TASK-001.md")},reviews:{},evidence:{},research:{},rules:{}} as any }
const start=(r=repo())=>({schema:"yaaw.evidence/v3",id:"EVIDENCE-TASK-001-S1",ticket:"TASK-001",ticket_revision:1,spec_revision:1,kind:"implementation_start",result:"STARTED",repository:r,workflow:"implementation.implement-ticket",commands:[],checks:[]});
const verify=(result="PASS",r=repo(),id="EVIDENCE-TASK-001-V1")=>({schema:"yaaw.evidence/v3",id,ticket:"TASK-001",ticket_revision:1,spec_revision:1,kind:"implementation_verification",result,repository:r,workflow:"implementation.verify-ticket",commands:[],checks:[]});
const review=(result="PASS",r=repo(),evidence=["EVIDENCE-TASK-001-V1"])=>doc({schema:"yaaw.review/v2",ticket:"TASK-001",round:1,result,ticket_revision:1,spec_revision:1,repository:r,evidence},".yaaw-core/project/reviews/TASK-001-R1.md");

describe("compact routing engine",()=>{
  it("derives aggregate state from ticket frontmatter",()=>{const a=artifacts("REPAIR_REQUIRED");const state=deriveState(a);expect(state.tickets["TASK-001"]).toBe("REPAIR_REQUIRED");expect(state.active_ticket).toBe("TASK-001");expect(state.planning.active_spec).toContain("SPEC-001.md")});
  it("adopts start evidence one transition at a time",()=>{const a=artifacts("READY");a.evidence[start().id]=start();const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.type).toBe("RECONCILE_REQUIRED");expect(p.reconciliation.to).toBe("IN_PROGRESS")});
  it("promotes only current PASS verification to review",()=>{const a=artifacts("IN_PROGRESS");a.evidence[verify().id]=verify();const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.reconciliation.id).toBe("IMPLEMENTATION_VERIFIED");expect(p.reconciliation.to).toBe("REVIEW_REQUIRED")});
  it("does not promote failed verification",()=>{const a=artifacts("IN_PROGRESS");a.evidence[verify("FAIL").id]=verify("FAIL");const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.type).toBe("ROUTE");expect(p.workflow).toBe("implementation.verify-ticket")});
  it("adopts a current independent review result",()=>{const a=artifacts("REVIEW_REQUIRED");a.evidence[verify().id]=verify();a.reviews["TASK-001-R1.md"]=review();const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.reconciliation.id).toBe("REVIEW_RESULT_UNAPPLIED");expect(p.reconciliation.to).toBe("PASS")});
  it("revokes stale PASS acceptance",()=>{const a=artifacts("PASS");a.evidence[verify("PASS",repo("sha256:old")).id]=verify("PASS",repo("sha256:old"));a.reviews["TASK-001-R1.md"]=review("PASS",repo("sha256:old"));const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.reconciliation.id).toBe("ACCEPTANCE_STALE");expect(p.reconciliation.to).toBe("REVIEW_REQUIRED")});
  it("routes actionable DRAFT to planner admission",()=>{const a=artifacts("DRAFT");const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.type).toBe("ROUTE");expect(p.workflow).toBe("planning.create-tickets")});
  it("routes a dependency-ready ticket before blocked dependents",()=>{const a=artifacts("READY");a.tickets["TASK-002"]=doc({schema:"yaaw.ticket/v1",id:"TASK-002",status:"READY",revision:1,spec:"SPEC-001",spec_revision:1,product_revision:1,engineering_revision:1,dependencies:["TASK-001"],expertise:[]},".yaaw-core/project/tickets/TASK-002.md");const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.ticket).toBe("TASK-001")});
  it("blocks multiple current accepted specs",()=>{const a=artifacts("READY");a.specs["SPEC-002"]=doc({schema:"yaaw.spec/v1",id:"SPEC-002",status:"ACCEPTED",revision:1,product_revision:1,engineering_revision:1},".yaaw-core/project/specs/SPEC-002.md");const p:any=planNext(kernel,deriveState(a),a,repo(),null);expect(p.type).toBe("RECONCILE_REQUIRED");expect(p.reconciliation.kind).toBe("BLOCKED")});
});
