import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { cp, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

const roots:string[]=[];const sourceSystem=resolve(".yaaw-core/system");
function git(root:string,...args:string[]){return execFileSync("git",["-C",root,...args],{encoding:"utf8"})}
async function walk(dir:string):Promise<string[]>{const out:string[]=[];for(const e of await readdir(dir,{withFileTypes:true})){const p=join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p)}return out}
async function sha256(path:string){return createHash("sha256").update(await readFile(path)).digest("hex")}
async function fixture(status="READY"){
  const root=await mkdtemp(join(tmpdir(),"yaaw-runtime-"));roots.push(root);await mkdir(join(root,".yaaw-core"),{recursive:true});await cp(sourceSystem,join(root,".yaaw-core/system"),{recursive:true});for(const dir of ["project/specs","project/tickets","project/evidence","project/reviews","project/research","project/rules","runtime","install"])await mkdir(join(root,".yaaw-core",dir),{recursive:true});
  await writeFile(join(root,".yaaw-core/project/product.md"),`---\nschema: yaaw.product/v1\nrevision: 1\nstatus: ready\n---\n# Product\n`);
  await writeFile(join(root,".yaaw-core/project/engineering.md"),`---\nschema: yaaw.engineering/v2\nrevision: 1\nstatus: ready\nproduct_revision: 1\ncurrent_frontier: FRONTIER-001\nreadiness: PASS\nscope_status: OPEN\n---\n# Engineering\n`);
  await writeFile(join(root,".yaaw-core/project/specs/SPEC-001.md"),`---\nschema: yaaw.spec/v1\nid: SPEC-001\nrevision: 1\nstatus: ACCEPTED\nproduct_revision: 1\nengineering_revision: 1\nfrontier_id: FRONTIER-001\ndecision_ids: []\n---\n# SPEC-001\n`);
  await writeFile(join(root,".yaaw-core/project/tickets/TASK-001.md"),`---\nschema: yaaw.ticket/v1\nid: TASK-001\nrevision: 1\nspec: SPEC-001\nspec_revision: 1\nproduct_revision: 1\nengineering_revision: 1\nstatus: ${status}\ndependencies: []\ndecision_ids: []\nexpertise: []\n---\n# TASK-001\n`);
  const managedFiles:Record<string,any>={};for(const path of await walk(join(root,".yaaw-core/system"))){const r=relative(root,path).replaceAll("\\","/");managedFiles[r]={owner:"package:system",sha256:await sha256(path),localOverride:false}}
  await writeFile(join(root,".yaaw-core/install/manifest.json"),JSON.stringify({schema:"yaaw.installation/v2",yaawVersion:"0.3.0-test",systemSchema:4,installationSchema:3,projectSchema:3,installedAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",project:{root:"."},integrations:{},skills:[],managedFiles,managedSections:{},managedConfigKeys:{}},null,2)+"\n");
  git(root,"init");git(root,"config","user.email","yaaw@example.test");git(root,"config","user.name","YAAW Test");git(root,"add",".");git(root,"commit","-m","fixture");return root;
}
function run(root:string,...extra:string[]){const tool=join(root,".yaaw-core/system/engine/runtime.mjs");try{return JSON.parse(execFileSync(process.execPath,[tool,"--workspace",root,...extra],{encoding:"utf8"}))}catch(error:any){const stdout=error?.stdout?.toString?.()??"";if(stdout)return JSON.parse(stdout);throw error}}
async function handoff(root:string){return JSON.parse(await readFile(join(root,".yaaw-core/runtime/handoff.json"),"utf8"))}
async function ticketStatus(root:string){const text=await readFile(join(root,".yaaw-core/project/tickets/TASK-001.md"),"utf8");return text.match(/^status:\s*(\S+)/m)?.[1]}
async function writeStart(root:string,repository:any){await writeFile(join(root,".yaaw-core/project/evidence/EVIDENCE-TASK-001-S1.json"),JSON.stringify({schema:"yaaw.evidence/v3",id:"EVIDENCE-TASK-001-S1",ticket:"TASK-001",ticket_revision:1,spec_revision:1,kind:"implementation_start",result:"STARTED",repository,workflow:"implementation.implement-ticket",commands:[],checks:[]},null,2)+"\n")}
async function writeVerification(root:string,repository:any,result="PASS",id="V1"){await writeFile(join(root,`.yaaw-core/project/evidence/EVIDENCE-TASK-001-${id}.json`),JSON.stringify({schema:"yaaw.evidence/v3",id:`EVIDENCE-TASK-001-${id}`,ticket:"TASK-001",ticket_revision:1,spec_revision:1,kind:"implementation_verification",result,repository,workflow:"implementation.verify-ticket",commands:[],checks:[]},null,2)+"\n")}
async function writeReview(root:string,repository:any,evidence=["EVIDENCE-TASK-001-V1"]){await writeFile(join(root,".yaaw-core/project/reviews/TASK-001-R1.md"),`---\nschema: yaaw.review/v2\nticket: TASK-001\nround: 1\nresult: PASS\nticket_revision: 1\nspec_revision: 1\nrepository:\n  schema: yaaw.repository-identity/v2\n  algorithm: yaaw-worktree-v3\n  status: READY\n  workspace_scope: .\n  git_root_relation: same\n  head_commit: ${repository.head_commit}\n  dirty: ${repository.dirty}\n  worktree_digest: ${repository.worktree_digest}\n  components: null\n  changed_paths: []\n  error: null\nevidence:\n${evidence.map(x=>`  - ${x}`).join("\n")}\n---\n# Review\n`)}
afterEach(async()=>{await Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true})))});

describe("compact orchestration runtime",()=>{
  it("prepares a workspace-relative v4 handoff and validates exact durable basis",async()=>{const root=await fixture();const prepared=run(root);expect(prepared.type).toBe("DISPATCH_READY");expect(prepared.workflow).toBe("implementation.implement-ticket");const h=await handoff(root);expect(h.schema).toBe("yaaw.handoff/v4");expect(h.references).toContain(".yaaw-core/project/tickets/TASK-001.md");expect(h.references.every((x:string)=>!x.startsWith(root))).toBe(true);expect(h.basis.ticket_status).toBe("READY");expect(run(root,"--check-handoff").type).toBe("HANDOFF_FRESH");await writeFile(join(root,".yaaw-core/runtime/observed-state.json"),"{\"replaceable\":true}\n");expect(run(root,"--check-handoff").type).toBe("HANDOFF_FRESH");await writeFile(join(root,".yaaw-core/project/product.md"),`---\nschema: yaaw.product/v1\nrevision: 1\nstatus: ready\n---\n# Product\nChanged semantic text.\n`);expect(run(root,"--check-handoff").type).toBe("HANDOFF_STALE")});
  it("reconstructs the same safe route after deleting runtime",async()=>{const root=await fixture();const first=run(root);await rm(join(root,".yaaw-core/runtime"),{recursive:true,force:true});const second=run(root);expect(second.type).toBe("DISPATCH_READY");expect(second.workflow).toBe(first.workflow);expect(second.ticket).toBe(first.ticket)});
  it("adopts implementation start and PASS verification into ticket frontmatter",async()=>{const root=await fixture();run(root);const repo=(await handoff(root)).repository;await writeStart(root,repo);let next=run(root);expect(next.type).toBe("RECONCILE_REQUIRED");expect(next.reconciliation.to).toBe("IN_PROGRESS");expect(run(root,"--reconcile-one").type).toBe("RECONCILED");expect(await ticketStatus(root)).toBe("IN_PROGRESS");await writeVerification(root,repo);next=run(root);expect(next.reconciliation.to).toBe("REVIEW_REQUIRED");expect(run(root,"--reconcile-one").type).toBe("RECONCILED");expect(await ticketStatus(root)).toBe("REVIEW_REQUIRED")});
  it("does not promote failed verification",async()=>{const root=await fixture();run(root);const repo=(await handoff(root)).repository;await writeStart(root,repo);run(root,"--reconcile-one");await writeVerification(root,repo,"FAIL");const next=run(root);expect(next.type).toBe("DISPATCH_READY");expect(next.workflow).toBe("implementation.verify-ticket");expect(await ticketStatus(root)).toBe("IN_PROGRESS")});
  it("adopts current independent review PASS",async()=>{const root=await fixture("REVIEW_REQUIRED");run(root);const inspected=run(root,"--inspect-only");const repo=JSON.parse(await readFile(join(root,".yaaw-core/runtime/observed-state.json"),"utf8")).repository;await writeVerification(root,repo);await writeReview(root,repo);const next=run(root);expect(next.type).toBe("RECONCILE_REQUIRED");expect(next.reconciliation.id).toBe("REVIEW_RESULT_UNAPPLIED");expect(next.reconciliation.to).toBe("PASS");expect(run(root,"--reconcile-one").type).toBe("RECONCILED");expect(await ticketStatus(root)).toBe("PASS");void inspected});
  it("routes DRAFT tickets to Planner admission",async()=>{const root=await fixture("DRAFT");const next=run(root);expect(next.type).toBe("DISPATCH_READY");expect(next.workflow).toBe("planning.create-tickets");expect(next.role).toBe("planner")});
});
