#!/usr/bin/env node
import { createHash } from "node:crypto";
import { access, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { parseFrontmatter } from "./frontmatter.mjs";
import { deriveState, planNext, chooseIntentTarget } from "./routing.mjs";

const hash=v=>"sha256:"+createHash("sha256").update(v).digest("hex");
const stable=value=>Array.isArray(value)?value.map(stable):(value&&typeof value==="object"?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value);
const same=(a,b)=>JSON.stringify(stable(a))===JSON.stringify(stable(b));
async function exists(path){try{await access(path);return true}catch{return false}}
async function json(path,fallback=null){try{return JSON.parse(await readFile(path,"utf8"))}catch{return fallback}}
async function meta(path){try{const raw=await readFile(path,"utf8");return{path,meta:parseFrontmatter(raw),digest:hash(Buffer.from(raw,"utf8"))}}catch{return null}}
async function list(dir,ext){try{return(await readdir(dir)).filter(x=>x.endsWith(ext)).sort()}catch{return[]}}
function execJson(file,workspace){const r=spawnSync(process.execPath,[file,"--workspace",workspace],{encoding:"utf8",windowsHide:true});let value=null;try{value=JSON.parse(r.stdout)}catch{}return value??{status:"UNKNOWN",error:r.stderr||`exit ${r.status}`}}
function argsOf(argv){const out={workspace:process.cwd(),invoke:null,inspect:false,reconcile:false,check:false};for(let i=0;i<argv.length;i+=1){const x=argv[i];if(x==="--workspace"&&argv[i+1]){out.workspace=argv[++i]}else if(x==="--invoke-skill"&&argv[i+1]){out.invoke=argv[++i]}else if(x==="--inspect-only")out.inspect=true;else if(x==="--reconcile-one")out.reconcile=true;else if(x==="--check-handoff")out.check=true;else throw new Error(`unknown argument: ${x}`)}return out}

async function inspectArtifacts(root){
  const p=join(root,".yaaw-core","project"),product=await meta(join(p,"product.md")),engineering=await meta(join(p,"engineering.md")),specs={},tickets={},reviews={},evidence={},research={},rules={};
  for(const name of await list(join(p,"specs"),".md")){const x=await meta(join(p,"specs",name));if(x?.meta?.id)specs[x.meta.id]=x}
  for(const name of await list(join(p,"tickets"),".md")){const x=await meta(join(p,"tickets",name));if(x?.meta?.id)tickets[x.meta.id]=x}
  for(const name of await list(join(p,"reviews"),".md")){const x=await meta(join(p,"reviews",name));if(x?.meta?.ticket)reviews[name]=x}
  for(const name of await list(join(p,"evidence"),".json")){const x=await json(join(p,"evidence",name));if(x?.id){x.path=join(p,"evidence",name);evidence[x.id]=x}}
  for(const name of await list(join(p,"research"),".md")){const x=await meta(join(p,"research",name));if(x)research[name]=x}
  for(const name of await list(join(p,"rules"),".md")){const x=await meta(join(p,"rules",name));if(x)rules[name]=x}
  return{product,engineering,specs,tickets,reviews,evidence,research,rules};
}
function frameworkBasis(i){return{yaaw_version:i.package_version??"unknown",system_schema:Number(i.system_schema??0),installation_schema:Number(i.installation_schema??0),project_schema:Number(i.project_schema??0),manifest_digest:i.manifest_digest??"unknown",integrity_status:i.status??"UNKNOWN"}}
function baseline(state,a){return{product_revision:state.product.revision,product_digest:a.product?.digest??null,engineering_revision:state.planning.revision,engineering_digest:a.engineering?.digest??null,planning_readiness:state.planning.readiness,active_spec:state.planning.active_spec,ticket_statuses:state.tickets}}
async function seedIntent(root,kernel,skillId,state,a){const s=kernel.skills[skillId];if(!s)throw new Error(`unknown skill ${skillId}`);const intent={schema:"yaaw.intent/v3",source_skill:skillId,desired_outcome:s.desired_outcome,requested_workflow:s.requested_workflow,target_artifact:chooseIntentTarget(s,state,a),completion_kind:s.completion_kind,created_from:baseline(state,a)};await mkdir(join(root,".yaaw-core","runtime"),{recursive:true});await writeFile(join(root,".yaaw-core","runtime","intent.json"),JSON.stringify(intent,null,2)+"\n");return intent}
function selectedSpec(state,a,ticket){const sid=ticket?a.tickets?.[ticket]?.meta?.spec:String(state.planning.active_spec??"").match(/SPEC-[0-9]+/)?.[0];return sid?a.specs?.[sid]??null:null}
function refsFor(reads,state,a,ticket){const refs=[];const push=x=>{if(x&&!refs.includes(x))refs.push(x)};for(const kind of reads){if(kind==="product")push(a.product?.path);else if(kind==="engineering")push(a.engineering?.path);else if(kind==="spec")push(selectedSpec(state,a,ticket)?.path);else if(kind==="ticket"){if(ticket)push(a.tickets?.[ticket]?.path);else Object.values(a.tickets??{}).forEach(x=>push(x.path))}else if(kind==="engineering_research")Object.values(a.research??{}).forEach(x=>push(x.path));else if(kind==="project_rule")Object.values(a.rules??{}).forEach(x=>push(x.path));else if(kind==="evidence")Object.values(a.evidence??{}).filter(x=>!ticket||x.ticket===ticket).forEach(x=>push(x.path));else if(kind==="review")Object.values(a.reviews??{}).filter(x=>!ticket||x.meta?.ticket===ticket).forEach(x=>push(x.path))}return refs}
function revisions(state,a,ticket){const spec=selectedSpec(state,a,ticket);return{product:Number(state.product.revision??0),engineering:Number(state.planning.revision??0),spec:Number(spec?.meta?.revision??0),ticket:Number(ticket?a.tickets?.[ticket]?.meta?.revision??0:0)}}
function basis(state,a,ticket){const spec=selectedSpec(state,a,ticket);return{product_digest:a.product?.digest??null,engineering_digest:a.engineering?.digest??null,spec_digest:spec?.digest??null,ticket_digest:ticket?a.tickets?.[ticket]?.digest??null:null,ticket_status:ticket?state.tickets?.[ticket]??null:null}}
function modulesFor(kernel,role,policy,a,ticket){const names=[...(policy.required_modules??[])];if(policy.ticket_modules&&ticket)for(const x of a.tickets?.[ticket]?.meta?.expertise??[])names.push(x);return[...new Set(names)].filter(name=>kernel.modules[name]?.usable_by?.includes(role)).map(name=>kernel.modules[name].path)}
function handoff(kernel,framework,state,a,repo,workflow,ticket,intent){const wf=kernel.workflows[workflow],policy=kernel.handoffs[workflow],role=kernel.roles[wf?.role];if(!wf||!policy||!role)throw new Error(`no handoff contract for ${workflow}`);for(const w of policy.writes??[])if(!role.writes.includes(w))throw new Error(`workflow ${workflow} writes unauthorized artifact ${w}`);return{schema:"yaaw.handoff/v4",framework:frameworkBasis(framework),role:wf.role,workflow,operation:wf.operation,instruction:{document:role.document,operation:wf.operation},desired_intent:intent?.desired_outcome??null,active_artifact:policy.active_artifact??null,ticket:ticket??null,references:refsFor(policy.reads,state,a,ticket),reads:policy.reads,writes:policy.writes,forbidden_writes:Object.keys(kernel.artifacts).filter(x=>!role.writes.includes(x)),revisions:revisions(state,a,ticket),basis:basis(state,a,ticket),expertise:modulesFor(kernel,wf.role,policy,a,ticket),host_expertise:[],expected_output:policy.expected_output,result_vocabulary:policy.result_vocabulary,repository_requirement:wf.repository_requirement,repository:repo}}
function repoAllowed(requirement,repo){if(requirement==="NONE")return true;if(requirement==="INSPECT")return repo?.status==="READY"||repo?.status==="UNVERSIONED";return repo?.status==="READY"}
function patchStatus(text,status){const lines=String(text).split(/\r?\n/);if(lines[0]?.trim()!=="---")throw new Error("ticket missing frontmatter");const end=lines.slice(1).findIndex(x=>x.trim()==="---");if(end<0)throw new Error("ticket missing closing frontmatter");const idx=lines.slice(1,end+1).findIndex(x=>/^status:\s*/.test(x));if(idx<0)throw new Error("ticket missing status");lines[idx+1]=`status: ${status}`;return lines.join("\n")}
async function observed(root,framework,repo,state,a,reconciliation){const value={schema:"yaaw.observed-state/v4",framework:{...frameworkBasis(framework),modified:framework.modified??[],missing:framework.missing??[],local_overrides:framework.local_overrides??[],repair_required:Boolean(framework.repair_required)},repository:repo,derived:state,reconstructable:true,artifacts:{product:a.product,engineering:a.engineering,specs:a.specs,tickets:a.tickets,reviews:a.reviews,evidence:a.evidence,research:a.research,rules:a.rules},inconsistencies:[],candidate_actions:[],reconciliation};await mkdir(join(root,".yaaw-core","runtime"),{recursive:true});await writeFile(join(root,".yaaw-core","runtime","observed-state.json"),JSON.stringify(value,null,2)+"\n");return value}

async function main(){
  const opt=argsOf(process.argv.slice(2)),root=resolve(opt.workspace),system=join(root,".yaaw-core","system"),runtime=join(root,".yaaw-core","runtime"),kernel=JSON.parse(await readFile(join(system,"kernel.yaml"),"utf8"));
  const integrity=execJson(join(system,"engine","integrity.mjs"),root);if(integrity.status!=="HEALTHY"){console.log(JSON.stringify({type:"FRAMEWORK_STOP",reason:`FRAMEWORK_${integrity.status}`,framework:integrity}));return}
  const repo=execJson(join(system,"engine","repository-identity.mjs"),root),a=await inspectArtifacts(root),state=deriveState(a);
  let intent=await json(join(runtime,"intent.json"));if(opt.invoke)intent=await seedIntent(root,kernel,opt.invoke,state,a);
  const planned=planNext(kernel,state,a,repo,intent),reconciliation=planned.type==="RECONCILE_REQUIRED"?planned.reconciliation:null;await observed(root,integrity,repo,state,a,reconciliation);
  if(opt.inspect){console.log(JSON.stringify({type:"INSPECTED",state,reconciliation}));return}
  if(opt.reconcile){if(!reconciliation){console.log(JSON.stringify({type:"NO_RECONCILIATION"}));return}if(reconciliation.kind==="BLOCKED"){console.log(JSON.stringify({type:"BLOCKED",reason:reconciliation.reason}));return}const ticket=a.tickets?.[reconciliation.subject];if(!ticket)throw new Error(`reconciliation ticket missing: ${reconciliation.subject}`);const raw=await readFile(ticket.path,"utf8");await writeFile(ticket.path,patchStatus(raw,reconciliation.to),"utf8");for(const file of ["observed-state.json","handoff.json"])try{await writeFile(join(runtime,file),"")}catch{}console.log(JSON.stringify({type:"RECONCILED",reconciliation}));return}
  if(opt.check){const old=await json(join(runtime,"handoff.json"));if(!old){console.log(JSON.stringify({type:"HANDOFF_STALE",reason:"missing handoff"}));return}const candidate=handoff(kernel,integrity,state,a,repo,old.workflow,old.ticket,intent);console.log(JSON.stringify(same(old,candidate)?{type:"HANDOFF_FRESH"}:{type:"HANDOFF_STALE",reason:"durable basis changed"}));return}
  if(planned.type!=="ROUTE"){if(planned.type!=="RECONCILE_REQUIRED")try{await writeFile(join(runtime,"handoff.json"),"")}catch{}console.log(JSON.stringify(planned));return}
  if(planned.terminal){console.log(JSON.stringify({type:"TERMINAL",terminal:planned.terminal}));return}if(planned.blocked){console.log(JSON.stringify({type:"BLOCKED",reason:planned.blocked,ticket:planned.ticket??null}));return}
  const wf=kernel.workflows[planned.workflow];if(!wf)throw new Error(`unknown workflow ${planned.workflow}`);if(wf.role==="orchestrator"){console.log(JSON.stringify({type:"ROOT_ACTION",workflow:planned.workflow,ticket:planned.ticket??null}));return}if(!repoAllowed(wf.repository_requirement,repo)){console.log(JSON.stringify({type:"BLOCKED",reason:"PRECONDITION_UNSATISFIED:REPOSITORY_IDENTITY_UNAVAILABLE",workflow:planned.workflow}));return}
  const h=handoff(kernel,integrity,state,a,repo,planned.workflow,planned.ticket??null,intent);await mkdir(runtime,{recursive:true});await writeFile(join(runtime,"handoff.json"),JSON.stringify(h,null,2)+"\n");console.log(JSON.stringify({type:"DISPATCH_READY",workflow:planned.workflow,role:h.role,operation:h.operation,ticket:h.ticket,handoff:join(runtime,"handoff.json")}));
}
main().catch(error=>{process.stdout.write(JSON.stringify({type:"FRAMEWORK_STOP",reason:"FRAMEWORK_CONTRACT_INCONSISTENCY",error:String(error?.stack??error)})+"\n");process.exitCode=2});
