#!/usr/bin/env node
import {spawnSync} from "node:child_process";
import {mkdir,readFile,readdir,rm,writeFile} from "node:fs/promises";
import {basename,join,resolve} from "node:path";
import {applyReconciliation,handoffBasis,planNext} from "./orchestration-engine.mjs";
import {parseFrontmatter} from "./frontmatter.mjs";

const argv=process.argv.slice(2);let workspaceArg=".",mode="prepare",invokeSkill=null;
for(let i=0;i<argv.length;i++){if(argv[i]==="--workspace"&&argv[i+1])workspaceArg=argv[++i];else if(argv[i]==="--inspect-only")mode="inspect";else if(argv[i]==="--check-handoff")mode="check";else if(argv[i]==="--reconcile-one")mode="reconcile";else if(argv[i]==="--invoke-skill"&&argv[i+1])invokeSkill=argv[++i];else{process.stderr.write("usage: orchestration-runtime.mjs [--workspace <path>] [--invoke-skill <id>] [--inspect-only|--check-handoff|--reconcile-one]\n");process.exit(2);}}
const workspace=resolve(workspaceArg),systemRoot=join(workspace,".yaaw-core","system"),projectRoot=join(workspace,".yaaw-core","project"),runtimeRoot=join(workspace,".yaaw-core","runtime");
const observedPath=join(runtimeRoot,"observed-state.json"),handoffPath=join(runtimeRoot,"handoff.json"),intentPath=join(runtimeRoot,"intent.json"),statePath=join(projectRoot,"state.json");
const json=async p=>JSON.parse(await readFile(p,"utf8"));const maybe=async p=>{try{return await json(p)}catch{return null}};const uniq=a=>[...new Set(a.filter(Boolean))];
async function fm(path){try{return parseFrontmatter(await readFile(path,"utf8"))}catch{return null}}
async function list(dir,re){try{return(await readdir(dir,{withFileTypes:true})).filter(x=>x.isFile()&&re.test(x.name)).map(x=>join(dir,x.name)).sort()}catch{return[]}}
function run(tool,args){const r=spawnSync(process.execPath,[tool,...args],{cwd:workspace,encoding:"utf8",windowsHide:true,maxBuffer:64*1024*1024});try{return JSON.parse(r.stdout||"{}")}catch{throw new Error((r.stderr||"").trim()||"invalid JSON from "+basename(tool))}}
function framework(raw,status=raw?.status??"UNKNOWN"){return{yaaw_version:String(raw?.package_version??"unknown"),system_schema:Number(raw?.system_schema??1),installation_schema:Number(raw?.installation_schema??1),project_schema:Number(raw?.project_schema??1),manifest_digest:String(raw?.manifest_digest??"sha256:unknown"),integrity_status:status,modified:Array.isArray(raw?.modified)?raw.modified:[],missing:Array.isArray(raw?.missing)?raw.missing:[],local_overrides:Array.isArray(raw?.local_overrides)?raw.local_overrides:[],repair_required:status!=="HEALTHY"}}
function repo(raw){return{schema:"yaaw.repository-identity/v2",algorithm:raw?.algorithm??null,status:raw?.status??"UNAVAILABLE",workspace_scope:String(raw?.workspace_scope??"."),git_root_relation:raw?.git_root_relation??"unknown",head_commit:raw?.head_commit??null,dirty:typeof raw?.dirty==="boolean"?raw.dirty:null,worktree_digest:raw?.worktree_digest??null,components:raw?.components??null,changed_paths:Array.isArray(raw?.changed_paths)?raw.changed_paths:[],error:raw?.error??null}}
async function contracts(){const names=["workflows","execution-policy","role-io","routing-policy","handoff-policy","artifacts","skills","transitions","reconciliation-policy"];const vals=await Promise.all(names.map(n=>json(join(systemRoot,"registries",n+".json"))));const c=Object.fromEntries(names.map((n,i)=>[n.replaceAll("-","_"),vals[i]])),errors=[];for(const[w,p]of Object.entries(c.handoff_policy.workflows??{})){const reg=c.workflows[w],ex=c.execution_policy.workflows?.[w],io=c.role_io.roles?.[reg?.role];if(!reg)errors.push("unknown workflow "+w);if(!ex)errors.push("no execution policy "+w);if(!io)errors.push("unknown role "+reg?.role);if(io){const br=(p.reads??[]).filter(x=>!io.reads.includes(x)),bw=(p.writes??[]).filter(x=>!io.writes.includes(x));if(br.length)errors.push(w+" bad reads "+br);if(bw.length)errors.push(w+" bad writes "+bw)}}return{...c,errors}}
const rel=p=>p.replace(workspace+"/","").replaceAll("\\","/"),specId=v=>String(v??"").match(/SPEC-[0-9]+/)?.[0]??null;
async function inspect(state){const pp=join(projectRoot,"product.md"),ep=join(projectRoot,"engineering.md"),specs={},tickets={},reviews=[],evidence=[];for(const p of await list(join(projectRoot,"specs"),/^SPEC-[0-9]+\.md$/)){const m=await fm(p);if(m?.id)specs[m.id]={path:rel(p),meta:m}}for(const p of await list(join(projectRoot,"tickets"),/^TASK-[0-9]+\.md$/)){const m=await fm(p);if(m?.id)tickets[m.id]={path:rel(p),meta:m}}for(const p of await list(join(projectRoot,"reviews"),/^TASK-[0-9]+-R[0-9]+\.md$/)){const v=await fm(p);if(v)reviews.push({path:rel(p),value:v})}for(const p of await list(join(projectRoot,"evidence"),/\.json$/)){try{evidence.push({path:rel(p),value:await json(p)})}catch{}}return{product:{path:rel(pp),meta:await fm(pp)},engineering:{path:rel(ep),meta:await fm(ep)},specs,tickets,reviews,evidence,research:(await list(join(projectRoot,"research"),/^RSH-.*\.md$/)).map(rel),rules:(await list(join(projectRoot,"rules"),/\.md$/)).map(rel),activeSpecId:specId(state?.planning?.active_spec)}}
function summary(a){return{product:a.product.meta?a.product:null,engineering:a.engineering.meta?a.engineering:null,specs:a.specs,tickets:a.tickets,reviews:a.reviews.map(x=>x.path),evidence:a.evidence.map(x=>x.path)}}
function requirement(r,repository){return r==="NONE"||r==="INSPECT"&&["READY","UNVERSIONED"].includes(repository.status)||r==="IDENTITY"&&repository.status==="READY"}
function refs(policy,a,ticket,state){const out=[];for(const x of policy.reads??[]){if(x==="product"&&a.product.meta)out.push(a.product.path);else if(x==="engineering"&&a.engineering.meta)out.push(a.engineering.path);else if(x==="spec"){const id=specId(state?.planning?.active_spec);if(id&&a.specs[id])out.push(a.specs[id].path)}else if(x==="ticket"&&ticket&&a.tickets[ticket])out.push(a.tickets[ticket].path);else if(x==="evidence")out.push(...a.evidence.map(v=>v.path));else if(x==="review")out.push(...a.reviews.map(v=>v.path));else if(x==="engineering_research")out.push(...a.research);else if(x==="project_rule")out.push(...a.rules);else if(x==="state")out.push(".yaaw-core/project/state.json")}return uniq(out)}
function revisions(state,a,ticket){const id=specId(state?.planning?.active_spec);return{product:Number(state?.product?.revision??0),engineering:Number(state?.planning?.revision??0),spec:Number(id?a.specs?.[id]?.meta?.revision??0:0),ticket:Number(ticket?a.tickets?.[ticket]?.meta?.revision??0:0)}}
async function expertise(policy,role,a,ticket){const reg=await json(join(systemRoot,"registries","expertise.json")),ids=[...(policy.required_expertise??[])];if(policy.ticket_expertise&&ticket&&Array.isArray(a.tickets?.[ticket]?.meta?.expertise))ids.push(...a.tickets[ticket].meta.expertise);return uniq(ids).filter(id=>reg[id]&&(reg[id].usable_by??[]).includes(role)).sort()}
function active(policy,a,ticket,state){if(policy.active_artifact==="product")return a.product.meta?a.product.path:null;if(policy.active_artifact==="engineering")return a.engineering.meta?a.engineering.path:null;if(policy.active_artifact==="spec"){const id=specId(state?.planning?.active_spec);return id?a.specs[id]?.path??null:null}if(policy.active_artifact==="ticket")return ticket?a.tickets[ticket]?.path??null:null;return null}
async function handoff(sel,c,state,a,fw,repository,intent){const reg=c.workflows[sel.workflow],p=c.handoff_policy.workflows[sel.workflow],ex=c.execution_policy.workflows[sel.workflow];if(!reg||!p||!ex)throw new Error("missing deterministic handoff contract for "+sel.workflow);const role=reg.role;return{schema:"yaaw.handoff/v3",framework:{yaaw_version:fw.yaaw_version,system_schema:fw.system_schema,installation_schema:fw.installation_schema,project_schema:fw.project_schema,manifest_digest:fw.manifest_digest,integrity_status:"HEALTHY"},role,workflow:sel.workflow,desired_intent:intent?.desired_outcome??p.desired_intent??null,active_artifact:active(p,a,sel.ticket,state),references:refs(p,a,sel.ticket,state),reads:uniq(p.reads??[]),writes:uniq(p.writes??[]),forbidden_writes:uniq(c.role_io.roles[role].forbidden_writes??[]),revisions:revisions(state,a,sel.ticket),expertise:await expertise(p,role,a,sel.ticket),host_expertise:[],expected_output:p.expected_output,result_vocabulary:uniq(p.result_vocabulary??[]),repository_requirement:ex.repository_requirement,repository,transition_sequence:Number(state.transition_sequence??0)}}
async function seed(skill,c,state){const s=c.skills[skill];if(!s)throw new Error("unknown public skill "+skill);const v={schema:"yaaw.intent/v2",source_skill:skill,desired_outcome:s.desired_outcome,requested_workflow:s.requested_workflow??s.workflow_id,target_artifact:null,completion_kind:s.completion_kind,created_from_transition_sequence:Number(state?.transition_sequence??0)};await mkdir(runtimeRoot,{recursive:true});await writeFile(intentPath,JSON.stringify(v,null,2)+"\n");return v}
const clear=async p=>rm(p,{force:true}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
async function main(){
 let raw;try{raw=run(join(systemRoot,"tools","framework-integrity.mjs"),["--workspace",workspace])}catch(e){raw={status:"UNKNOWN",error:String(e)}}let fw=framework(raw),c;try{c=await contracts()}catch(e){return{schema:"yaaw.orchestration-runtime/v2",status:"FRAMEWORK_STOP",reason:"FRAMEWORK_CONTRACT_INCONSISTENCY",error:String(e)}}if(c.errors.length)fw=framework(raw,"CONTRACT_INCONSISTENT");
 let rr;try{rr=run(join(systemRoot,"tools","repository-identity.mjs"),["--workspace",workspace])}catch(e){rr={status:"UNAVAILABLE",workspace_scope:".",git_root_relation:"unknown",error:String(e)}}const repository=repo(rr);let state=await maybe(statePath);if(invokeSkill)await seed(invokeSkill,c,state);const intent=await maybe(intentPath),a=await inspect(state);
 const p=planNext({framework:fw,repository,state,artifacts:a,evidence:a.evidence,reviews:a.reviews,intent,transitions:c.transitions,routingPolicy:c.routing_policy,reconciliationPolicy:c.reconciliation_policy});
 const observed={schema:"yaaw.observed-state/v3",framework:fw,repository,transition_sequence:Number(state?.transition_sequence??0),claims:state??{},artifacts:summary(a),inconsistencies:c.errors.map(x=>"FRAMEWORK_CONTRACT_INCONSISTENCY:"+x),candidate_actions:[],reconciliation:p.reconciliation??null};
 const persist=async()=>{await mkdir(runtimeRoot,{recursive:true});await writeFile(observedPath,JSON.stringify(observed,null,2)+"\n")};
 if(p.kind==="FRAMEWORK_STOP"){observed.candidate_actions=["INSTALLER_REPAIR"];if(mode!=="check"){await persist();await clear(handoffPath)}return{schema:"yaaw.orchestration-runtime/v2",status:"FRAMEWORK_STOP",reason:p.reason,observed}}
 if(p.kind==="RECONCILE_REQUIRED"){observed.candidate_actions=["orchestration.reconcile-state"];if(mode==="reconcile"){state=applyReconciliation(state,p.reconciliation,repository);await writeFile(statePath,JSON.stringify(state,null,2)+"\n");observed.transition_sequence=state.transition_sequence;observed.claims=state;await persist();await clear(handoffPath);return{schema:"yaaw.orchestration-runtime/v2",status:"RECONCILED",reconciliation:p.reconciliation,state}}if(mode!=="check"){await persist();await clear(handoffPath)}return{schema:"yaaw.orchestration-runtime/v2",status:"RECONCILE_REQUIRED",workflow:"orchestration.reconcile-state",reconciliation:p.reconciliation,observed}}
 if(p.kind==="INTENT_COMPLETE"){observed.candidate_actions=["INTENT_COMPLETE"];if(mode!=="check"){await persist();await clear(handoffPath);await clear(intentPath)}return{schema:"yaaw.orchestration-runtime/v2",status:"INTENT_COMPLETE",completion_kind:intent?.completion_kind??null,observed}}
 if(mode==="inspect"){observed.candidate_actions=[p.workflow??p.terminal??p.reason??p.kind];await persist();return{schema:"yaaw.orchestration-runtime/v2",status:"INSPECTED",observed}}
 if(["ROOT_ACTION","TERMINAL","BLOCKED"].includes(p.kind)){observed.candidate_actions=[p.workflow??p.terminal??p.reason??p.kind];if(mode!=="check"){await persist();await clear(handoffPath)}return{schema:"yaaw.orchestration-runtime/v2",status:p.kind,workflow:p.workflow??null,terminal:p.terminal??null,reason:p.reason??null,observed}}
 const ex=c.execution_policy.workflows[p.workflow];if(!requirement(ex.repository_requirement,repository)){if(mode!=="check"){await persist();await clear(handoffPath)}return{schema:"yaaw.orchestration-runtime/v2",status:"BLOCKED",terminal:"BLOCKED",reason:ex.repository_requirement==="IDENTITY"?"REPOSITORY_IDENTITY_UNAVAILABLE":"REPOSITORY_INSPECTION_UNAVAILABLE",workflow:p.workflow,observed}}
 const h=await handoff(p,c,state,a,fw,repository,intent);observed.candidate_actions=[p.workflow];
 if(mode==="check"){const old=await maybe(handoffPath);return old&&same(old,h)?{schema:"yaaw.orchestration-runtime/v2",status:"HANDOFF_FRESH",...handoffBasis({selected:p,state,intent})}:{schema:"yaaw.orchestration-runtime/v2",status:"HANDOFF_STALE",workflow:p.workflow,reason:"HANDOFF_BASIS_CHANGED"}}
 await persist();await writeFile(handoffPath,JSON.stringify(h,null,2)+"\n");return{schema:"yaaw.orchestration-runtime/v2",status:"DISPATCH_READY",workflow:h.workflow,role:h.role,handoff:h}
}
try{const r=await main();process.stdout.write(JSON.stringify(r,null,2)+"\n");process.exitCode=["DISPATCH_READY","INSPECTED","HANDOFF_FRESH","ROOT_ACTION","TERMINAL","RECONCILED","INTENT_COMPLETE"].includes(r.status)?0:2}catch(e){process.stdout.write(JSON.stringify({schema:"yaaw.orchestration-runtime/v2",status:"FRAMEWORK_STOP",reason:"FRAMEWORK_CONTRACT_INCONSISTENCY",error:String(e?.message??e)},null,2)+"\n");process.exitCode=2}
