#!/usr/bin/env node
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root=resolve(fileURLToPath(new URL("../",import.meta.url))),packagePath=join(root,"package.json"),systemSource=join(root,".yaaw-core/system/SYSTEM.md"),npmCliCandidates=[process.env.npm_execpath,join(dirname(process.execPath),"node_modules","npm","bin","npm-cli.js"),join(dirname(process.execPath),"..","lib","node_modules","npm","bin","npm-cli.js")].filter(Boolean),npmCli=npmCliCandidates.find(x=>existsSync(x));if(!npmCli)throw new Error(`Could not locate npm CLI beside Node: ${process.execPath}`);
function run(args,options={}){const r=spawnSync(process.execPath,[npmCli,...args],{cwd:options.cwd??root,encoding:"utf8",stdio:options.capture?"pipe":"inherit",env:{...process.env,NO_COLOR:"1",FORCE_COLOR:"0",YAAW_DISABLE_AUTO_UPDATE:"1"}});if(r.status!==0)throw new Error(`Command failed (${r.status}): npm ${args.join(" ")}\n${r.stdout??""}\n${r.stderr??""}`);return r.stdout??""}function pack(){const p=JSON.parse(run(["pack","--json","--ignore-scripts"],{capture:true}));return join(root,p[0].filename)}const execTarball=(tarball,args,capture=false)=>run(["exec","--yes",`--package=${tarball}`,"--","yaaw-se",...args],{capture});
const originalPackage=await readFile(packagePath,"utf8"),originalSystem=await readFile(systemSource,"utf8"),temp=await mkdtemp(join(tmpdir(),"yaaw-update-smoke-")),project=join(temp,"consumer-project");await mkdir(project);const tarballs=[];
try{const pkg=JSON.parse(originalPackage),currentVersion=pkg.version,oldVersion=`${currentVersion}-update-smoke.0`;pkg.version=oldVersion;await writeFile(packagePath,JSON.stringify(pkg,null,2)+"\n");run(["run","build"]);const oldTarball=pack();tarballs.push(oldTarball);execTarball(oldTarball,["install","--directory",project,"--tools","codex","--skills","core","--yes"]);
  await rm(join(project,".codex"),{recursive:true,force:true});const manifestPath=join(project,".yaaw-core/install/manifest.json"),legacy=JSON.parse(await readFile(manifestPath,"utf8"));legacy.integrations.codex.adapterVersion=1;delete legacy.integrations.codex.runtime;delete legacy.integrations.codex.configuration;legacy.managedFiles=Object.fromEntries(Object.entries(legacy.managedFiles).filter(([rel])=>!rel.startsWith(".codex/")));delete legacy.managedConfigKeys;await writeFile(manifestPath,JSON.stringify(legacy,null,2)+"\n");
  const durable={"product.md":"product sentinel\n","engineering.md":"engineering sentinel\n","research/RSH-001.md":"research sentinel\n","specs/SPEC-001.md":"spec sentinel\n","tickets/TASK-001.md":"ticket sentinel\n","reviews/TASK-001-R1.md":"review sentinel\n","evidence/test.json":"{\"sentinel\":\"evidence\"}\n","rules/custom.md":"rule sentinel\n"};for(const [rel,bytes] of Object.entries(durable)){const path=join(project,".yaaw-core/project",rel);await mkdir(dirname(path),{recursive:true});await writeFile(path,bytes)}
  const installedSystem=join(project,".yaaw-core/system/SYSTEM.md"),canonical=await readFile(installedSystem,"utf8"),tainted=canonical+"\nincident framework self-edit\n";await writeFile(installedSystem,tainted);const runtime=join(project,".yaaw-core/runtime");for(const name of ["observed-state.json","handoff.json","intent.json","dispatch-failures.json"])await writeFile(join(runtime,name),"{}\n");
  await writeFile(packagePath,originalPackage);const marker=`\n<!-- synthetic-package-update-${currentVersion} -->\n`;await writeFile(systemSource,originalSystem+marker);run(["run","build"]);const currentTarball=pack();tarballs.push(currentTarball);execTarball(currentTarball,["install","--directory",project,"--action","repair","--conflict-policy","backup-replace","--yes"]);
  for(const [rel,expected] of Object.entries(durable)){if(await readFile(join(project,".yaaw-core/project",rel),"utf8")!==expected)throw new Error(`Durable artifact changed: ${rel}`)}if(existsSync(join(project,".yaaw-core/project/state.json")))throw new Error("compact update created project/state.json");const repaired=await readFile(installedSystem,"utf8");if(!repaired.includes(`synthetic-package-update-${currentVersion}`))throw new Error("compact SYSTEM.md did not update");for(const name of ["observed-state.json","handoff.json","intent.json","dispatch-failures.json"])if(existsSync(join(runtime,name)))throw new Error(`runtime cache survived repair: ${name}`);let backup=false;for(const stamp of await readdir(join(project,".yaaw-core/install/backups"))){const candidate=join(project,".yaaw-core/install/backups",stamp,".yaaw-core/system/SYSTEM.md");if(existsSync(candidate)&&await readFile(candidate,"utf8")===tainted)backup=true}if(!backup)throw new Error("tainted compact framework bytes were not backed up");const manifest=JSON.parse(await readFile(manifestPath,"utf8"));if(manifest.yaawVersion!==currentVersion)throw new Error("manifest version did not update");if(manifest.integrations?.codex?.adapterVersion!==5)throw new Error("Codex adapter did not migrate to v5");if(!existsSync(join(project,".codex/yaaw-runtime.md")))throw new Error("Codex runtime surface not restored");const doctor=JSON.parse(execTarball(currentTarball,["doctor","--directory",project,"--json"],true));if(!doctor.healthy)throw new Error(`Doctor failed after compact update: ${JSON.stringify(doctor)}`);console.log(`✓ compact tarball repair ${oldVersion} -> ${currentVersion} preserved durable artifacts and restored framework`)
}finally{await writeFile(packagePath,originalPackage);await writeFile(systemSource,originalSystem);for(const t of tarballs)await rm(t,{force:true});await rm(temp,{recursive:true,force:true});try{run(["run","build"])}catch{}}
