#!/usr/bin/env node
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
const root=resolve(fileURLToPath(new URL("../",import.meta.url))),npmCliCandidates=[process.env.npm_execpath,join(dirname(process.execPath),"node_modules","npm","bin","npm-cli.js"),join(dirname(process.execPath),"..","lib","node_modules","npm","bin","npm-cli.js")].filter(Boolean),npmCli=npmCliCandidates.find(x=>existsSync(x));if(!npmCli)throw new Error(`Could not locate npm CLI beside Node: ${process.execPath}`);
function run(args,options={}){const r=spawnSync(process.execPath,[npmCli,...args],{cwd:options.cwd??root,encoding:"utf8",stdio:options.capture?"pipe":"inherit",env:{...process.env,NO_COLOR:"1",FORCE_COLOR:"0",YAAW_DISABLE_AUTO_UPDATE:"1"}});if(r.status!==0)throw new Error(`Command failed (${r.status}): npm ${args.join(" ")}\n${r.stdout??""}\n${r.stderr??""}`);return r.stdout??""}
const provided=process.env.YAAW_SMOKE_TARBALL?resolve(process.env.YAAW_SMOKE_TARBALL):null;let owns=false,tarball;if(provided){if(!existsSync(provided))throw new Error(`Provided smoke tarball does not exist: ${provided}`);tarball=provided}else{const info=JSON.parse(run(["pack","--json","--ignore-scripts"],{capture:true}));tarball=join(root,info[0].filename);owns=true}
const execTarball=(args,capture=false)=>run(["exec","--yes",`--package=${tarball}`,"--","yaaw-se",...args],{capture});
const surfaces={codex:{root:".agents",skills:".agents/skills",bootstrap:"AGENTS.md"},"claude-code":{root:".claude",skills:".claude/skills",bootstrap:"CLAUDE.md"},"gemini-cli":{root:".gemini",skills:".gemini/skills",bootstrap:"GEMINI.md"},cline:{root:".cline",skills:".cline/skills",bootstrap:".cline/rules/yaaw-se.md"}};
const expectedSystem=["SYSTEM.md","engine","kernel.yaml","modules","roles","schemas","templates"].sort(),expectedProject=["engineering.md","evidence","product.md","research","reviews","rules","specs","tickets"].sort();
const entries=async p=>(await readdir(p)).sort();function same(actual,expected,label){if(JSON.stringify([...actual].sort())!==JSON.stringify([...expected].sort()))throw new Error(`${label}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`)}
async function layout(project,tools){const manifest=JSON.parse(await readFile(join(project,".yaaw-core/install/manifest.json"),"utf8"));same(await entries(join(project,".yaaw-core")),["install","project","runtime","system"],".yaaw-core");same(await entries(join(project,".yaaw-core/system")),expectedSystem,"system");same(await entries(join(project,".yaaw-core/project")),expectedProject,"project");same(await entries(join(project,".yaaw-core/runtime")),[],"runtime");if(existsSync(join(project,".yaaw-core/project/state.json")))throw new Error("legacy project/state.json leaked into compact install");for(const id of tools){const s=surfaces[id];same(await entries(join(project,s.skills)),manifest.skills,`${id} skills`);const bootstrap=await readFile(join(project,s.bootstrap),"utf8");if(!bootstrap.includes(".yaaw-core/system/kernel.yaml"))throw new Error(`${id}: bootstrap missing compact kernel`)}if(tools.includes("codex")){if(!existsSync(join(project,".codex/yaaw-runtime.md")))throw new Error("Codex runtime missing");if(existsSync(join(project,".codex/agents/yaaw-orchestrator.toml")))throw new Error("Orchestrator child must not exist")}}
async function smoke(name,tools,opts={}){const base=await mkdtemp(join(tmpdir(),`yaaw-tarball-${name}-`)),project=opts.pathWithSpaces||opts.unicode?join(base,opts.unicode?"proyecto-测试":"project with spaces"):base;if(project!==base)await mkdir(project);try{if(tools.includes("codex"))await writeFile(join(project,"AGENTS.md"),"consumer-owned line\n");execTarball(["install","--directory",project,"--tools",tools.join(","),"--skills","core","--yes"]);await layout(project,tools);const product=join(project,".yaaw-core/project/product.md");await writeFile(product,`durable sentinel: ${name}\n`);execTarball(["install","--directory",project,"--action","quick-update","--yes"]);if(await readFile(product,"utf8")!==`durable sentinel: ${name}\n`)throw new Error("quick update changed durable memory");await layout(project,tools);const status=JSON.parse(execTarball(["status","--directory",project,"--json"],true)),doctor=JSON.parse(execTarball(["doctor","--directory",project,"--json"],true));if(!status.healthy||!doctor.healthy)throw new Error(`${name}: unhealthy install ${JSON.stringify({status,doctor})}`);console.log(`✓ tarball smoke: ${name}`)}finally{await rm(base,{recursive:true,force:true})}}
try{await smoke("codex",["codex"],{pathWithSpaces:true});await smoke("claude",["claude-code"]);await smoke("gemini",["gemini-cli"],{unicode:true});await smoke("cline",["cline"]);await smoke("all",["codex","claude-code","gemini-cli","cline"]);console.log(`Exact tarball smoke passed: ${basename(tarball)}`)}finally{if(owns)await rm(tarball,{force:true})}
