import { readdir, readFile, stat } from "node:fs/promises";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
const root=fileURLToPath(new URL("../",import.meta.url)),payload=join(root,"dist","payload"),errors=[],packageMetadata=JSON.parse(await readFile(join(root,"package.json"),"utf8")),payloadMetadata=JSON.parse(await readFile(join(payload,"payload.json"),"utf8"));if(payloadMetadata.version!==packageMetadata.version)errors.push(`payload version ${payloadMetadata.version} does not match package version ${packageMetadata.version}`);
async function walk(dir){const out=[];for(const entry of await readdir(dir,{withFileTypes:true})){const full=join(dir,entry.name);if(entry.isDirectory())out.push(...await walk(full));else out.push(full)}return out}
const all=await walk(payload),rels=all.map(p=>relative(payload,p).replaceAll("\\","/"));for(const rel of rels){if(rel.includes("/tests/")||rel.startsWith("tests/"))errors.push(`tests shipped: ${rel}`);if(rel==="yaaw-core/project"||rel.startsWith("yaaw-core/project/"))errors.push(`durable project data shipped: ${rel}`);if(rel==="yaaw-core/runtime"||rel.startsWith("yaaw-core/runtime/"))errors.push(`runtime state shipped: ${rel}`);if(rel==="yaaw-core/install"||rel.startsWith("yaaw-core/install/"))errors.push(`installer state shipped: ${rel}`);if(/\.(pem|key|p12|pfx)$/i.test(rel)||/(^|\/)(\.env|id_rsa|id_ed25519)$/i.test(rel))errors.push(`possible secret shipped: ${rel}`)}
for(const rel of ["yaaw-core/system/SYSTEM.md","yaaw-core/system/kernel.yaml","yaaw-core/system/roles/orchestrator.md","yaaw-core/system/roles/planner.md","yaaw-core/system/roles/implementer.md","yaaw-core/system/roles/reviewer.md","yaaw-core/system/modules/changeability.md","yaaw-core/system/engine/integrity.mjs","yaaw-core/system/engine/repository-identity.mjs","yaaw-core/system/engine/routing.mjs","yaaw-core/system/engine/runtime.mjs","yaaw-core/system/schemas/evidence-v3.schema.json","yaaw-core/system/schemas/intent.schema.json","integrations/codex/yaaw-runtime.md"])if(!rels.includes(rel))errors.push(`missing compact runtime payload: ${rel}`);
for(const legacy of ["core","workflows","rules","registries","expertise","tools"])if(rels.some(x=>x.startsWith(`yaaw-core/system/${legacy}/`)))errors.push(`legacy semantic directory shipped: yaaw-core/system/${legacy}`);
const kernel=JSON.parse(await readFile(join(payload,"yaaw-core","system","kernel.yaml"),"utf8")),skills=kernel.skills??{},workflows=kernel.workflows??{},skillDirs=(await readdir(join(payload,"skills"),{withFileTypes:true})).filter(x=>x.isDirectory()).map(x=>x.name).sort();if(JSON.stringify(skillDirs)!==JSON.stringify(Object.keys(skills).sort()))errors.push("kernel skill catalog/payload directory mismatch");for(const [skillId,entry] of Object.entries(skills)){const path=join(payload,"skills",skillId,"SKILL.md");let text;try{text=await readFile(path,"utf8")}catch{errors.push(`missing public skill ${skillId}`);continue}if(!text.startsWith("---\n"))errors.push(`${skillId}: frontmatter must begin on line 1`);if(!text.includes(`name: ${skillId}`))errors.push(`${skillId}: mismatched name`);if(!workflows[entry.requested_workflow])errors.push(`${skillId}: unresolved workflow ${entry.requested_workflow}`);if(!text.includes("system/engine/runtime.mjs"))errors.push(`${skillId}: does not use compact runtime`)}
for(const [id,entry] of Object.entries(workflows)){const role=kernel.roles?.[entry.role];if(!role)errors.push(`${id}: unknown role ${entry.role}`);else try{await stat(join(payload,role.document.replace(/^\.yaaw-core\/system\//,"yaaw-core/system/")))}catch{errors.push(`${id}: missing role document ${role.document}`)}}
const generated=JSON.parse(await readFile(join(payload,"yaaw-core","registries","skills.json"),"utf8"));if(JSON.stringify(Object.keys(generated).sort())!==JSON.stringify(Object.keys(skills).sort()))errors.push("generated CLI skill discovery metadata disagrees with kernel");
for(const file of all){if(!/\.(md|json|ts|js|mjs|yaml)$/i.test(file))continue;const text=await readFile(file,"utf8");if(/BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY/.test(text))errors.push(`private key material in ${relative(payload,file)}`)}
if(errors.length){console.error("YAAW npm payload verification failed:");errors.forEach(e=>console.error(`- ${e}`));process.exit(1)}console.log(`YAAW npm payload verified: ${all.length} files.`);
